---
abstract: unknown
author:
  - 'Daniel Kasak <dan@entropy.homelinux.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.82, CPAN::Meta::Converter version 2.132510'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Gtk2-Ex-DBI
no_index:
  directory:
    - t
    - inc
requires:
  DBI: 1.3
  Gtk2: 1.04
  Gtk2::Ex::Dialogs: 0.08
version: 2.30
